USE LAPD_Crime_Data;

CREATE TABLE crime_data (
    DR_NO BIGINT NOT NULL,
    Date_Rptd DATE NOT NULL,
    DATE_OCC DATE NOT NULL,
    TIME_OCC TIME NOT NULL,
    AREA INT NOT NULL,
    AREA_NAME VARCHAR(255) NOT NULL,
    Rpt_Dist_No INT NOT NULL,
    Part_1_2 INT NOT NULL,
    Crm_Cd INT NOT NULL,
    Crm_Cd_Desc VARCHAR(255) NOT NULL,
    Mocodes TEXT NULL,
    Vict_Age INT NOT NULL,
    Vict_Sex FLOAT,
    Vict_Descent VARCHAR(255),
    Premis_Cd FLOAT,
    Premis_Desc VARCHAR(255),
    Weapon_Used_Cd FLOAT,
    Weapon_Desc VARCHAR(255),
    Status VARCHAR(10) NOT NULL,
    Status_Desc VARCHAR(255) NOT NULL,
    Crm_Cd_1 FLOAT NULL,
    Crm_Cd_2 FLOAT NULL,
    Crm_Cd_3 FLOAT NULL,
    Crm_Cd_4 FLOAT NULL,
    LOCATION TEXT NOT NULL,
    Cross_Street TEXT,
    LAT FLOAT NOT NULL,
    LON FLOAT NOT NULL,
    Year INT NOT NULL,
    Month INT NOT NULL,
    Date_Time DATETIME NOT NULL,
    Temperature_C FLOAT NOT NULL,
    Dew_point_C FLOAT NOT NULL,
    Humidity FLOAT NOT NULL,
    Precipitation_mm FLOAT NOT NULL,
    Wind_Direction FLOAT NOT NULL,
    Windspeed_kmh FLOAT NOT NULL,
    Air_pressure_hPa FLOAT NOT NULL,
    Rainy_Day INT NOT NULL
);
